name: surveyy
description: Survey Y Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  get: ^4.6.6
  objectbox: ^2.3.1
  dio: ^5.3.2
  file_picker: ^6.0.0
  objectbox_flutter_libs: ^2.3.1
  path_provider: ^2.1.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  objectbox_generator: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/right-bg.png
    - assets/images/Icon.png
    - assets/images/profilepic.jfif
    - assets/images/Upload.png
